language: cpp

before_install:
  - uname -a
  - lsb_release --all
  - sudo apt-get --assume-yes update

install:
  - sudo apt-get --assume-yes install libX11-dev
  - sudo apt-get --assume-yes install libfltk1.3-dev
  - sudo apt-get --assume-yes install libfontconfig1-dev
  - sudo apt-get --assume-yes install libglu1-mesa-dev
  - sudo apt-get --assume-yes install libice-dev
  - sudo apt-get --assume-yes install libjpeg-dev
  - sudo apt-get --assume-yes install libjpeg62-dev
  - sudo apt-get --assume-yes install libpng-dev
  - sudo apt-get --assume-yes install libpng12-dev
  - sudo apt-get --assume-yes install libx11-dev
  - sudo apt-get --assume-yes install libxcursor-dev
  - sudo apt-get --assume-yes install libxext-dev
  - sudo apt-get --assume-yes install libxft-dev
  - sudo apt-get --assume-yes install libxi-dev
  - sudo apt-get --assume-yes install libxinerama-dev
  - sudo apt-get --assume-yes install libxrender-dev
  - sudo apt-get --assume-yes install libz-dev
  - sudo apt-get --assume-yes install mesa-common-dev
  - sudo apt-get --assume-yes install mingw32
  - sudo apt-get --assume-yes install mingw32-binutils
  - sudo apt-get --assume-yes install mingw32-runtime
  - sudo apt-get --assume-yes install wine
  - sudo apt-get --assume-yes install zlib1g-dev

env:
  - TRCC=gcc TRCXX=g++
  - TRCC=clang TRCXX=clang++
  - TRCC=i586-mingw32msvc-gcc TRCXX=i586-mingw32msvc-g++

script:
  - export CC=$TRCC
  - export CXX=$TRCXX
  - ${TRAVIS_BUILD_DIR}/build-o-matic.sh

matrix:
  allow_failures:
    - env: TRCC=clang TRCXX=clang++
    - env: TRCC=i586-mingw32msvc-gcc TRCXX=i586-mingw32msvc-g++
  fast_finish: true
